#!/usr/bin/env python3
"""Emit the PE import table for one DLL as SH assembly (a replacement for dlltool).

Modern binutils' dlltool has dropped its SuperH machine table, but the assembler and linker
still handle everything an import table needs: the `.rva` directive yields an image-relative
(rva32) relocation, and ld's PE linker script gathers the `.idata$N` sections and appends the
directory terminator. So we write the classic layout ourselves:

  .idata$2  one IMAGE_IMPORT_DESCRIPTOR (ILT rva, timestamp, forwarder, name rva, IAT rva)
  .idata$4  import lookup table: rva of each hint/name entry, then 0
  .idata$5  import address table: same content until the loader patches it; each entry is
            the symbol `__imp__<Name>` that the calling-convention thunks jump through
  .idata$6  hint/name entries (WORD hint, ASCIIZ name), 2-byte aligned
  .idata$7  the DLL name

All five carry the "w" flag so the merged .idata section is writable: the Windows CE loader
patches the import address table in place.

Usage: mkimplib.py <dll name> <table.txt>   (table format as for gen_thunks.py)
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_thunks import parse_table  # noqa: E402


def _tag(dll: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in dll)


def render(dll: str, names: list[str]) -> str:
    if not dll or any(c.isspace() for c in dll):
        raise ValueError(f"bad DLL name {dll!r}")
    if not names:
        raise ValueError("import table is empty")
    tag = _tag(dll)
    out = [
        f"! Generated by mkimplib.py for {dll}; do not edit.",
        "\t.section .idata$2,\"w\"",
        f"\t.rva\t.Lilt_{tag}",
        "\t.long\t0",
        "\t.long\t0",
        f"\t.rva\t.Lname_{tag}",
        f"\t.rva\t.Liat_{tag}",
        "",
        "\t.section .idata$4,\"w\"",
        f".Lilt_{tag}:",
    ]
    out += [f"\t.rva\t.Lhn_{n}" for n in names]
    out += ["\t.long\t0", "", "\t.section .idata$5,\"w\"", f".Liat_{tag}:"]
    for n in names:
        out += [f"\t.globl\t__imp__{n}", f"__imp__{n}:", f"\t.rva\t.Lhn_{n}"]
    out += ["\t.long\t0", "", "\t.section .idata$6,\"w\""]
    for n in names:
        out += ["\t.align\t1", f".Lhn_{n}:", "\t.short\t0", f'\t.asciz\t"{n}"']
    out += ["", "\t.section .idata$7,\"w\"", f".Lname_{tag}:", f'\t.asciz\t"{dll}"', ""]
    return "\n".join(out)


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        sys.stderr.write("usage: mkimplib.py <dll name> <table.txt>\n")
        return 2
    try:
        with open(argv[2], encoding="utf-8") as fh:
            entries = parse_table(fh)
        sys.stdout.write(render(argv[1], [e.name for e in entries]))
    except (OSError, ValueError) as exc:
        sys.stderr.write(f"mkimplib: {exc}\n")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
