#!/usr/bin/env python3
"""Emit the PE import tables for one or more DLLs as SH assembly (a replacement for dlltool).

Modern binutils' dlltool has dropped its SuperH machine table, but the assembler and linker
still handle everything an import table needs: the `.rva` directive yields an image-relative
(rva32) relocation, and ld's PE linker script gathers the `.idata$N` sections and appends the
directory terminator. So we write the classic layout ourselves:

  .idata$2  one IMAGE_IMPORT_DESCRIPTOR per DLL (ILT rva, timestamp, forwarder, name, IAT)
  .idata$4  import lookup tables: rva of each hint/name entry, then 0, per DLL
  .idata$5  import address tables: same content until the loader patches it; each entry is
            the symbol `__imp__<Name>` that the calling-convention thunks jump through
  .idata$6  hint/name entries (WORD hint, ASCIIZ name), 2-byte aligned
  .idata$7  the DLL names

All DLLs go into ONE object on purpose: the assembler pads every section to 16 bytes, while
the loader reads 20-byte descriptors back to back, so descriptors from separate objects would
be misaligned (the second DLL's address table then never gets patched and the first call into
it jumps into the name strings). All five sections carry the "w" flag so the merged .idata
section is writable: the Windows CE loader patches the import address table in place.

Usage: mkimplib.py <dll name>=<table.txt> [<dll name>=<table.txt> ...]
       (table format as for gen_thunks.py)
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_thunks import parse_table  # noqa: E402


def _tag(dll: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in dll)


def render(modules: list[tuple[str, list[str]]]) -> str:
    if not modules:
        raise ValueError("no import tables given")
    for dll, names in modules:
        if not dll or any(c.isspace() for c in dll):
            raise ValueError(f"bad DLL name {dll!r}")
        if not names:
            raise ValueError(f"import table for {dll} is empty")
    seen: set[str] = set()
    for _, names in modules:
        for n in names:
            if n in seen:
                raise ValueError(f"duplicate import name {n}")
            seen.add(n)
    out = ["! Generated by mkimplib.py; do not edit.", "\t.section .idata$2,\"w\""]
    for dll, _ in modules:
        tag = _tag(dll)
        out += [f"\t.rva\t.Lilt_{tag}", "\t.long\t0", "\t.long\t0", f"\t.rva\t.Lname_{tag}", f"\t.rva\t.Liat_{tag}"]
    out += ["", "\t.section .idata$4,\"w\""]
    for dll, names in modules:
        out.append(f".Lilt_{_tag(dll)}:")
        out += [f"\t.rva\t.Lhn_{n}" for n in names]
        out.append("\t.long\t0")
    out += ["", "\t.section .idata$5,\"w\""]
    for dll, names in modules:
        out.append(f".Liat_{_tag(dll)}:")
        for n in names:
            out += [f"\t.globl\t__imp__{n}", f"__imp__{n}:", f"\t.rva\t.Lhn_{n}"]
        out.append("\t.long\t0")
    out += ["", "\t.section .idata$6,\"w\""]
    for _, names in modules:
        for n in names:
            out += ["\t.align\t1", f".Lhn_{n}:", "\t.short\t0", f'\t.asciz\t"{n}"']
    out += ["", "\t.section .idata$7,\"w\""]
    for dll, _ in modules:
        out += [f".Lname_{_tag(dll)}:", f'\t.asciz\t"{dll}"']
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        sys.stderr.write("usage: mkimplib.py <dll>=<table.txt> ...\n")
        return 2
    try:
        modules = []
        for spec in argv[1:]:
            if "=" not in spec:
                raise ValueError(f"expected <dll>=<table>, got {spec!r}")
            dll, path = spec.split("=", 1)
            with open(path, encoding="utf-8") as fh:
                modules.append((dll, [e.name for e in parse_table(fh)]))
        sys.stdout.write(render(modules))
    except (OSError, ValueError) as exc:
        sys.stderr.write(f"mkimplib: {exc}\n")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
