#!/usr/bin/env python3
"""Emit a C array of wide-string import names from an import table (for hello.exe's check)."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_thunks import parse_table  # noqa: E402


def render(names: list[str]) -> str:
    body = ",\n".join(f'    L"{n}"' for n in names)
    return "/* Generated by mknames.py; do not edit. */\nstatic const WCHAR *const IMPORT_NAMES[] = {\n" + body + "\n};\n"


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        sys.stderr.write("usage: mknames.py <table.txt>\n")
        return 2
    try:
        with open(argv[1], encoding="utf-8") as fh:
            sys.stdout.write(render([e.name for e in parse_table(fh)]))
    except (OSError, ValueError) as exc:
        sys.stderr.write(f"mknames: {exc}\n")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
