#!/usr/bin/env python3
"""Emit C arrays of import names per DLL from import tables (for hello.exe's run-time check).

Usage: mknames.py tools/imports/coredll.txt tools/imports/winsock.txt ...
The DLL name is the table's file stem plus ".dll".
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_thunks import parse_table  # noqa: E402


def render(tables: list[tuple[str, list[str]]]) -> str:
    out = ["/* Generated by mknames.py; do not edit. */",
           "typedef struct import_module { const WCHAR *dll; const WCHAR *const *names; unsigned count; } import_module;"]
    for dll, names in tables:
        ident = dll.replace(".", "_")
        body = ",\n".join(f'    L"{n}"' for n in names)
        out.append(f"static const WCHAR *const IMPORT_NAMES_{ident}[] = {{\n{body}\n}};")
    out.append("static const import_module IMPORT_MODULES[] = {")
    for dll, names in tables:
        ident = dll.replace(".", "_")
        out.append(f'    {{ L"{dll}", IMPORT_NAMES_{ident}, {len(names)} }},')
    out.append("};")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        sys.stderr.write("usage: mknames.py <table.txt>...\n")
        return 2
    try:
        tables = []
        for path in argv[1:]:
            with open(path, encoding="utf-8") as fh:
                tables.append((Path(path).stem + ".dll", [e.name for e in parse_table(fh)]))
        sys.stdout.write(render(tables))
    except (OSError, ValueError) as exc:
        sys.stderr.write(f"mknames: {exc}\n")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
