/* The subset of the Windows CE 2.11 coredll.dll API used by this project.
 *
 * Every function is declared with an assembler label that points at the import thunk
 * generated by tools/gen_thunks.py (see the calling-convention notes there). The thunk name
 * is `_xt_<Name>`; the table of names and argument counts lives in tools/coredll_imports.txt
 * and must stay in sync with this header (tests/test_headers.py checks that).
 *
 * Only the wide-character ("W") entry points exist on Windows CE. The loader resolves a
 * missing import to NULL instead of failing, so every name here was verified against the
 * device's coredll (hello.exe checks them at run time).
 */
#ifndef CE_API_H
#define CE_API_H

#include "ce_types.h"

#define CE_IMPORT(name) __asm__("_xt_" #name)

/* Kernel: processes, threads, synchronisation */
HANDLE CreateThread(LPSECURITY_ATTRIBUTES, DWORD stack, LPTHREAD_START_ROUTINE, LPVOID, DWORD flags, LPDWORD id) CE_IMPORT(CreateThread);
VOID   ExitThread(DWORD) CE_IMPORT(ExitThread);
BOOL   TerminateThread(HANDLE, DWORD) CE_IMPORT(TerminateThread);
BOOL   SetThreadPriority(HANDLE, int) CE_IMPORT(SetThreadPriority);
int    GetThreadPriority(HANDLE) CE_IMPORT(GetThreadPriority);
VOID   Sleep(DWORD ms) CE_IMPORT(Sleep);
DWORD  GetTickCount(VOID) CE_IMPORT(GetTickCount);
HANDLE CreateEventW(LPSECURITY_ATTRIBUTES, BOOL manual, BOOL initial, LPCWSTR name) CE_IMPORT(CreateEventW);
BOOL   EventModify(HANDLE, DWORD op) CE_IMPORT(EventModify);
#define EVENT_PULSE 1
#define EVENT_RESET 2
#define EVENT_SET   3
#define SetEvent(h)   EventModify((h), EVENT_SET)      /* CE 2.11 coredll has no SetEvent export */
#define ResetEvent(h) EventModify((h), EVENT_RESET)
HANDLE CreateMutexW(LPSECURITY_ATTRIBUTES, BOOL owner, LPCWSTR name) CE_IMPORT(CreateMutexW);
BOOL   ReleaseMutex(HANDLE) CE_IMPORT(ReleaseMutex);
DWORD  WaitForSingleObject(HANDLE, DWORD ms) CE_IMPORT(WaitForSingleObject);
BOOL   CloseHandle(HANDLE) CE_IMPORT(CloseHandle);
VOID   InitializeCriticalSection(LPCRITICAL_SECTION) CE_IMPORT(InitializeCriticalSection);
VOID   DeleteCriticalSection(LPCRITICAL_SECTION) CE_IMPORT(DeleteCriticalSection);
VOID   EnterCriticalSection(LPCRITICAL_SECTION) CE_IMPORT(EnterCriticalSection);
VOID   LeaveCriticalSection(LPCRITICAL_SECTION) CE_IMPORT(LeaveCriticalSection);
DWORD  GetLastError(VOID) CE_IMPORT(GetLastError);
VOID   SetLastError(DWORD) CE_IMPORT(SetLastError);
VOID   GetSystemInfo(LPSYSTEM_INFO) CE_IMPORT(GetSystemInfo);
BOOL   GetVersionExW(LPOSVERSIONINFOW) CE_IMPORT(GetVersionExW);
VOID   GetLocalTime(LPSYSTEMTIME) CE_IMPORT(GetLocalTime);
BOOL   QueryPerformanceCounter(PLARGE_INTEGER) CE_IMPORT(QueryPerformanceCounter);
BOOL   QueryPerformanceFrequency(PLARGE_INTEGER) CE_IMPORT(QueryPerformanceFrequency);

/* Modules */
HMODULE LoadLibraryW(LPCWSTR) CE_IMPORT(LoadLibraryW);
BOOL    FreeLibrary(HMODULE) CE_IMPORT(FreeLibrary);
PVOID   GetProcAddressW(HMODULE, LPCWSTR) CE_IMPORT(GetProcAddressW);

/* Memory */
LPVOID VirtualAlloc(LPVOID, DWORD size, DWORD type, DWORD protect) CE_IMPORT(VirtualAlloc);
BOOL   VirtualFree(LPVOID, DWORD size, DWORD type) CE_IMPORT(VirtualFree);
BOOL   VirtualCopy(LPVOID dst, LPVOID src, DWORD size, DWORD protect) CE_IMPORT(VirtualCopy);
HLOCAL LocalAlloc(UINT flags, UINT bytes) CE_IMPORT(LocalAlloc);
HLOCAL LocalFree(HLOCAL) CE_IMPORT(LocalFree);

/* Files */
HANDLE CreateFileW(LPCWSTR, DWORD access, DWORD share, LPSECURITY_ATTRIBUTES, DWORD disposition, DWORD flags, HANDLE tmpl) CE_IMPORT(CreateFileW);
BOOL   ReadFile(HANDLE, LPVOID, DWORD, LPDWORD, LPOVERLAPPED) CE_IMPORT(ReadFile);
BOOL   WriteFile(HANDLE, LPCVOID, DWORD, LPDWORD, LPOVERLAPPED) CE_IMPORT(WriteFile);
DWORD  SetFilePointer(HANDLE, LONG, PLONG, DWORD) CE_IMPORT(SetFilePointer);
BOOL   FlushFileBuffers(HANDLE) CE_IMPORT(FlushFileBuffers);
BOOL   DeleteFileW(LPCWSTR) CE_IMPORT(DeleteFileW);
BOOL   DeviceIoControl(HANDLE, DWORD code, LPVOID in, DWORD inlen, LPVOID out, DWORD outlen, LPDWORD ret, LPOVERLAPPED) CE_IMPORT(DeviceIoControl);

/* Registry */
LONG RegOpenKeyExW(HKEY, LPCWSTR, DWORD, DWORD, PHKEY) CE_IMPORT(RegOpenKeyExW);
LONG RegCreateKeyExW(HKEY, LPCWSTR, DWORD, LPWSTR cls, DWORD opts, DWORD sam, LPSECURITY_ATTRIBUTES, PHKEY, LPDWORD disp) CE_IMPORT(RegCreateKeyExW);
LONG RegQueryValueExW(HKEY, LPCWSTR, LPDWORD, LPDWORD type, LPBYTE, LPDWORD) CE_IMPORT(RegQueryValueExW);
LONG RegSetValueExW(HKEY, LPCWSTR, DWORD, DWORD type, const BYTE *, DWORD) CE_IMPORT(RegSetValueExW);
LONG RegDeleteKeyW(HKEY, LPCWSTR) CE_IMPORT(RegDeleteKeyW);
LONG RegCloseKey(HKEY) CE_IMPORT(RegCloseKey);

/* Device manager (stream drivers) */
HANDLE RegisterDevice(LPCWSTR type, DWORD index, LPCWSTR lib, DWORD info) CE_IMPORT(RegisterDevice);
BOOL   DeregisterDevice(HANDLE) CE_IMPORT(DeregisterDevice);

/* User interface (used by the test tools and the terminal app) */
int  MessageBoxW(HWND, LPCWSTR text, LPCWSTR caption, UINT type) CE_IMPORT(MessageBoxW);
VOID OutputDebugStringW(LPCWSTR) CE_IMPORT(OutputDebugStringW);

/* Generic indirect calls into Microsoft-compiled code (function pointers from
 * GetProcAddressW, e.g. Card Services). Arguments are passed as 32-bit words. */
UINT32 xt_call0(PVOID fn) __asm__("_xt_call0");
UINT32 xt_call1(PVOID fn, UINT32) __asm__("_xt_call1");
UINT32 xt_call2(PVOID fn, UINT32, UINT32) __asm__("_xt_call2");
UINT32 xt_call3(PVOID fn, UINT32, UINT32, UINT32) __asm__("_xt_call3");
UINT32 xt_call4(PVOID fn, UINT32, UINT32, UINT32, UINT32) __asm__("_xt_call4");
UINT32 xt_call5(PVOID fn, UINT32, UINT32, UINT32, UINT32, UINT32) __asm__("_xt_call5");
UINT32 xt_call6(PVOID fn, UINT32, UINT32, UINT32, UINT32, UINT32, UINT32) __asm__("_xt_call6");
UINT32 xt_call7(PVOID fn, UINT32, UINT32, UINT32, UINT32, UINT32, UINT32, UINT32) __asm__("_xt_call7");
UINT32 xt_call8(PVOID fn, UINT32, UINT32, UINT32, UINT32, UINT32, UINT32, UINT32, UINT32) __asm__("_xt_call8");

#endif /* CE_API_H */
